# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c66b2ae560d2defd48482bb501b5855c2e6fe1d996bedb69e390d08cb38f99cec5d2c29ed6b4b3900dbff2e9f054ca184d5af5bd686908925a99cf21b9153506

test:
  secret_key_base: 7e81cd6f8a0312cd78ea651453804d7ca47e4b347a0b5cadb2788b4b58125013931cfcf773543618b64a954e2202ad9af9f797443c6b60434a35a7f38453f0db

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
